---
- hosts: all
  #gather_facts: no

  vars:
    ansible_network_os: icx
    ansible_user: cli
    # ansible_become: True
    ansible_password: fibranne
    ansible_become_method: enable
    ansible_become_pass: fibranne
    # ansible_command_timeout: 4800
    ansible_persistent_log_messages: True
    ansible_buffer_read_timeout : 10


  tasks:
  - name: upgrade firmware using tftp
    icx_firmware_upgrade:
     server_type: tftp
     server_address: 10.177.17.24
     partition: secondary
     filename: shashikumar/SPR08095_b437ufi.bin
    #  filename: shashikumar/TNR08095_b437ufi.bin
     boot_only: False
     save_running_config: False
  #     #working
