---
- hosts: all
  gather_facts: yes
  vars:
    ansible_network_os: icx
    ansible_become: True
    ansible_user: cli
    ansible_password: fibranne
    ansible_become_method: enable
    ansible_become_pass: fibranne
    # ansible_python_interpreter: /usr/bin/python3.5
    ansible_persistent_log_messages: True
    ansible_buffer_read_timeout : 3
#    
        
  tasks:
          #- name: test 1
          #icx_qos:
          #queue_name:
          #old_name: que6
          #new_name: qosp6

  - name : test 2
    icx_qos :
      egress_buffer_profile_7X50:
        queue_share_level: level4-1/9
        user_profile_name: egress4
        queue_number: 4
        # state: absent
  # - name : test 3
  #   icx_qos :
  #     attach_egress_buffer_profile:
  #       port: '1/1/11'
  #       profile_name: euser7
  #       state: present
  #       # state: present
  #     check_running_config: True


  # - name: test4
  #   icx_qos:
  #     dscp_priority:
  #       dscp_value: 0 1 2 3 4
  #       priority: '2'
  #       state: present
 
        #
  # - name  : test 5
  #   icx_qos :
  #     egress_buffer_profile_7150:
  #         port_share_level: level4-1/9
  #         user_profile_name: euser7
  #         state: present
            #

  #  - name: test 6
  #  icx_qos:     
  #     egress_shape_ifg_bytes:
  #       value_in_bytes: 127
  #       state: present

          #

  # - name: test 7
  #  icx_qos:
  #    ingress_buffer_profile:
  #      priority_group_number: 1
  #      shared_level: level4-1/9
  #      user_profile_name: iuser1
  #      state: absent

  #- name: test8
  #  icx_qos:
  #   internal_trunk_queue:
  #        level: level5-1/5
  #        queue: 4
  #        state: present

 

 

 

    register: result

  - debug:
           msg: '{{ result }}'   