---
- hosts: all
  gather_facts: no
  vars:
    ansible_network_os: icx
    ansible_user: cli
    ansible_password: fibranne
    ansible_persistent_log_messages: True

  tasks:
  # - name: ping to host
  #   icx_ping:
  #     dest: 10.45.2.119
  #   register: output

  - name: ping to host
    icx_ping:
      dest: 172.16.10.202
    register: output
  
  # - name: ping to host
  #   icx_ping:
  #     dest: 172.16.10.204
  #   register: output

  - name: show command
    debug:
      msg: '{{ output }}'

  
